name: Scrape Weekly Leaders (ET)

on:
  # Scheduled run every 5 minutes, 8 AM - 1 AM ET Fri/Sat/Sun (DST-proof)
  schedule:
    - cron: '*/5 11-23,0-5 * * 5,6,0'
  # Run immediately on pushes to main (for testing)
  push:
    branches:
      - main
  # Manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York  # Makes 'date' show ET

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show next 5 scheduled runs (ET)
        run: |
          pip install croniter pytz
          python - <<'EOF'
          from croniter import croniter
          from datetime import datetime
          import pytz

          # GitHub Actions cron
          cron = "*/5 11-23,0-5 * * 5,6,0"

          # Current UTC time
          now_utc = datetime.utcnow()
          iter = croniter(cron, now_utc)

          eastern = pytz.timezone("America/New_York")

          print("Next 5 scheduled runs (ET):")
          for _ in range(5):
              next_run_utc = iter.get_next(datetime)
              next_run_et = next_run_utc.replace(tzinfo=pytz.utc).astimezone(eastern)
              print(next_run_et.strftime("%Y-%m-%d %H:%M %Z"))
          EOF

      - name: Log timestamp (ET)
        run: date

      - name: Run scraper with failsafe
        run: python generate_json_safe.py

      - name: Upload weekly.json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: weekly-json
          path: weekly.json

      - name: Commit and push JSON via SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin git@github.com:dargo01/cfb-weekly-leaders.git
          git add weekly.json
          git commit -m "Update weekly.json" || echo "No changes to commit"
          git push
